version: '3.3'

services:

  frps:
    image: tiggomark/frps:latest
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7500:7500"


  nginx_frps:
    image: nginx
    container_name: nginx_frps
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fullchain.pem:/etc/letsencrypt/live/tiggomark.com.br/fullchain.pem
      - ./privkey.pem:/etc/letsencrypt/live/tiggomark.com.br/privkey.pem



